"""
LLM-Enhanced Identity Formation Experiment.

Same design as identity_formation.py but using Claude-powered interpretation.
Watch how LLM emplotment produces richer, more contextual interpretations
while the same architectural mechanisms (memory selection, character formation)
operate underneath.

Requires ANTHROPIC_API_KEY in environment or .env file.
"""

import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from dotenv import load_dotenv
load_dotenv()

from narrative_agents.core import Experience, Telos
from narrative_agents.llm_core import LLMNarrativeAgent


def run_llm_identity_formation():
    print("=" * 70)
    print("  LLM-ENHANCED IDENTITY FORMATION EXPERIMENT")
    print("  (Ricoeur's emplotment powered by Claude)")
    print("=" * 70)

    # Identical experiences for all agents
    experiences = [
        Experience("error", "Failed to parse input correctly", "system_crash", -0.7),
        Experience("success", "Completed complex task efficiently", "user_satisfaction", 0.8),
        Experience("error", "Database connection timeout under load", "recovery_needed", -0.5),
        Experience("neutral", "Processed routine request", "normal_operation", 0.0),
        Experience("error", "Invalid state transition in workflow", "logic_error", -0.6),
        Experience("success", "Optimised algorithm — 3x speedup", "improvement", 0.9),
        Experience("error", "Memory overflow during batch processing", "resource_limit", -0.8),
        Experience("success", "User satisfaction score exceeded target", "goal_met", 0.7),
        Experience("neutral", "Logged standard metrics", "monitoring", 0.1),
        Experience("error", "Unexpected null reference in production", "bug_found", -0.4),
    ]

    # Three agents with different teloi
    agents = {
        "Scholar": LLMNarrativeAgent(name="Scholar", telos=Telos.LEARNING),
        "Performer": LLMNarrativeAgent(name="Performer", telos=Telos.PERFORMING),
        "Explorer": LLMNarrativeAgent(name="Explorer", telos=Telos.EXPLORING),
    }

    # Feed identical experiences
    print(f"\nFeeding {len(experiences)} identical experiences to 3 agents...\n")

    for exp in experiences:
        print(f"  Experience: [{exp.type}] {exp.content}")
        for name, agent in agents.items():
            memory = agent.experience(exp)
            marker = "CORE" if memory.relevance > 0.7 else "peripheral"
            print(f"    {name:>12}: {memory.interpretation[:65]} [{marker}]")
        print()

    # Results
    print("=" * 70)
    print("  RESULTING IDENTITIES")
    print("=" * 70)

    for name, agent in agents.items():
        stats = agent.memory_efficiency()
        print(f"\n  {name} (telos: {agent.telos.value}):")
        print(f"    Core memories: {stats['core_memories']} / {stats['total_experiences']}")
        print(f"    Memory efficiency: {stats['memory_efficiency']:.1f}%")
        if agent.virtues:
            print(f"    Virtues: {list(agent.virtues.keys())}")
        if agent.vices:
            print(f"    Vices: {list(agent.vices.keys())}")

    # Narratives
    print("\n" + "=" * 70)
    print("  AGENT NARRATIVES (generated by Claude)")
    print("=" * 70)

    for name, agent in agents.items():
        print(f"\n--- {name}'s Story ---")
        print(agent.tell_story())

    # Cost summary
    print("\n" + "=" * 70)
    print("  USAGE SUMMARY")
    print("=" * 70)

    total_calls = 0
    total_tokens = 0
    for name, agent in agents.items():
        s = agent.usage_stats
        calls = s['api_calls']
        tokens = s['input_tokens'] + s['output_tokens']
        total_calls += calls
        total_tokens += tokens
        print(f"  {name}: {calls} API calls, {tokens:,} tokens")

    print(f"\n  Total: {total_calls} API calls, {total_tokens:,} tokens")

    print("\n" + "=" * 70)
    print("  PHILOSOPHICAL POINT")
    print("=" * 70)
    print("""
    With LLM-powered emplotment, the interpretations are no longer limited
    to predefined mappings. The same architectural mechanisms — selective
    memory, character formation, identity-based decision-making — now
    operate on richer, contextually aware meanings.

    The philosophy hasn't changed. The depth of interpretation has.
    Ricoeur's insight scales with the sophistication of the interpreter.
    """)


if __name__ == "__main__":
    run_llm_identity_formation()
